name: Android Release

on:
  push:
    tags:
      - 'v*.*'

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: write  # اضافه کردن  نوشتن

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set up Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: '8.7'

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Build with Gradle
      run: ./gradlew assembleRelease

    - name: List files
      run: ls -R app/build/outputs/apk/

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release.apk
        path: app/build/outputs/apk/release/app-release.apk

    - name: Create GitHub Release
      run: |
        curl -X POST \
          -H "Authorization: token ${{ secrets.PAT_GITHUB }}" \
          -H "Content-Type: application/json" \
          -d '{
            "tag_name": "${{ github.ref_name }}",
            "target_commitish": "main",
            "name": "Release ${{ github.ref_name }}",
            "body": "Description of the release",
            "draft": false,
            "prerelease": false
          }' \
          https://api.github.com/repos/davudsedft/purlite/releases

    - name: Upload Release Asset
      run: |
        release_id=$(curl -H "Authorization: token ${{ secrets.PAT_GITHUB }}" https://api.github.com/repos/davudsedft/purlite/releases/tags/${{ github.ref_name }} | jq -r '.id')
        curl -X POST \
          -H "Authorization: token ${{ secrets.PAT_GITHUB }}" \
          -H "Content-Type: application/vnd.android.package-archive" \
          --data-binary @app/build/outputs/apk/release/app-release.apk \
          https://uploads.github.com/repos/davudsedft/purlite/releases/$release_id/assets?name=app-release.apk
